FROM node:16.20.2-alpine AS build

WORKDIR /usr/local/app/frontend

COPY package.json .

RUN npm run install

COPY . .

EXPOSE 3000


FROM node:16.20.2-alpine AS prod

WORKDIR /usr/local/app/frontend

COPY --from=build /usr/local/app/frontend /usr/local/app/frontend

CMD [ "npm", "start" ]