services:
  redis-server:
    image: "redis"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - /app/backend/node_modules
      - ./backend:/app/backend
