services:
  redis-server:
    image: "redis"
    restart: always
    networks:
      - drc-bridge-net

  frontend:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    networks:
      - drc-bridge-net

  backend:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - drc-bridge-net

networks:
  drc-bridge-net:
    driver: bridge
