FROM node:16.20.2-alpine AS build

WORKDIR /usr/local/app/backend

COPY package.json .

RUN npm run install

COPY . .

EXPOSE 8080


FROM node:16.20.2-alpine AS prod

WORKDIR /usr/local/app/backend

COPY --from=build /usr/local/app/backend /usr/local/app/backend

CMD [ "npm", "start" ]